# permissions for end users to view cloudcontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudcontroller-viewer-role
rules:
- apiGroups:
  - unifi.thebsdbox.co.uk
  resources:
  - cloudcontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - unifi.thebsdbox.co.uk
  resources:
  - cloudcontrollers/status
  verbs:
  - get
