
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - unifi.thebsdbox.co.uk
  resources:
  - cloudcontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - unifi.thebsdbox.co.uk
  resources:
  - cloudcontrollers/finalizers
  verbs:
  - update
- apiGroups:
  - unifi.thebsdbox.co.uk
  resources:
  - cloudcontrollers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - unifi.thebsdbox.co.uk
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - unifi.thebsdbox.co.uk
  resources:
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - unifi.thebsdbox.co.uk
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
