# permissions for end users to view directions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: directions-viewer-role
rules:
- apiGroups:
  - katnav.fnnrn.me
  resources:
  - directions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - katnav.fnnrn.me
  resources:
  - directions/status
  verbs:
  - get
