# permissions for end users to edit directions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: directions-editor-role
rules:
- apiGroups:
  - katnav.fnnrn.me
  resources:
  - directions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - katnav.fnnrn.me
  resources:
  - directions/status
  verbs:
  - get
