
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - katnav.fnnrn.me
  resources:
  - directions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - katnav.fnnrn.me
  resources:
  - directions/finalizers
  verbs:
  - update
- apiGroups:
  - katnav.fnnrn.me
  resources:
  - directions/status
  verbs:
  - get
  - patch
  - update
